services:
  sts34:
    restart: always
    image: sts34
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 8080:8080
    networks:
      - net03
    depends_on:
      - db

  db:
    restart: always
    image: mysql:lts
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=xe
      - MYSQL_USER=scott
      - MYSQL_PASSWORD=tiger
    # volumes:
    #   - ./dbdata:/var/lib/mysql
    networks:
      - net03

networks:
  net03:
    external: true
    # driver: bridge