CREATE TABLE `bbs05` (
	`num` INT NOT NULL AUTO_INCREMENT,
	`sub` VARCHAR(50) NULL DEFAULT NULL,
	`content` TEXT NULL,
	`cnt` INT NULL,
	`nalja` TIMESTAMP NULL DEFAULT (now()),
	PRIMARY KEY (`num`)
)
COLLATE='utf8mb4_0900_ai_ci'
;


/*
MYSQL PAGING query

-- case 1
SELECT * FROM 
(SELECT * FROM bbs05 LIMIT 10 OFFSET 194) AS A
ORDER BY num DESC;

SELECT * FROM 
(SELECT * FROM bbs05 LIMIT 194,10) AS A
ORDER BY num DESC;

-- case 2
SELECT * FROM bbs05 ORDER BY num DESC LIMIT 0,10;
SELECT * FROM bbs05 ORDER BY num DESC LIMIT 10,10;
SELECT * FROM bbs05 ORDER BY num DESC LIMIT 20,10;

-- case3
SELECT * FROM 
	(SELECT * FROM bbs05 
		WHERE num>(SELECT MAX(num)-10 FROM bbs05) 
		AND num<(SELECT MAX(num)-0+1 FROM bbs05)
	LIMIT 10) AS A
ORDER BY num DESC;

SELECT * FROM 
	(SELECT * FROM bbs05 
		WHERE num>(SELECT MAX(num)-20 FROM bbs05) 
		AND num<(SELECT MAX(num)-10+1 FROM bbs05)
	LIMIT 10) AS A
ORDER BY num DESC;

SELECT * FROM 
	(SELECT * FROM bbs05 
		WHERE num>(SELECT MAX(num)-210 FROM bbs05) 
		AND num<(SELECT MAX(num)-200+1 FROM bbs05)
	LIMIT 10) AS A
ORDER BY num DESC;

*/